#140 show submission fail
openmsupply/application-manager-web-app pull request #235
Opened 2021-01-04 04:11 UTC by nmadruga

Fixes #140

Branched off PR #234, please merge that one before this one!

To be used with back-end running PR [138F](https://github.com/openmsupply/application-manager-server/pull/163)

## Changes
- The awaiting part was already done as part of PR #234 
- Separate existing modal window on `ApplicationPageWrapper` in component to be reused by `ApplicationOverview`
- Show warning message in case there is a problem found in any response during the **submission step**.

## Existing problems - not resolved
- There is a problem with checking for unique user names - it considers the username entered in the current application and throws an error when trying to submit on the first time (which is actually good for testing the Modal) - Need a separated issue.
- Sometimes the warning is showing right after clicking to create the new application!

2021-01-07 21:03 UTC, CarlosNZ requested changes
> ~~There is a problem with checking for unique user names - it considers the username entered in the current application and throws an error when trying to submit on the first time (which is actually good for testing the Modal) - Need a separated issue.~~ SOLVED

This is not quite solved. (Note: I'm using it with latest master merged back in, with my evaluator changes.) Sometimes it works, sometimes it doesn't. Can't quite figure out what the conditions are.

2021-01-07 21:40 UTC, CarlosNZ commented
> > ~There is a problem with checking for unique user names - it considers the username entered in the current application and throws an error when trying to submit on the first time (which is actually good for testing the Modal) - Need a separated issue.~ SOLVED
> 
> This is not quite solved. (Note: I'm using it with latest master merged back in, with my evaluator changes.) Sometimes it works, sometimes it doesn't. Can't quite figure out what the conditions are.

I _think_ this part is solved for now. We should keep an eye on it.

However, there's a problem with the reverse situation, in that the application is submitted fine (no modal) even when it should have failed submission validation.

Steps to reproduce:
- Fill in User Registration form
- Get to Summary page
- Manually edit the database to change an existing username to the new one you're trying to submit
- Submit form -- it goes through correctly when it shouldn't have.
- If you go back to the application page, it correctly re-routes and shows the error, so it's doing the revalidation correctly then.

2021-01-07 22:10 UTC, CarlosNZ commented
> However, there's a problem with the reverse situation, in that the application is submitted fine (no modal) even when it should have failed submission validation.

This is fixed now. Problem was that `setInvalidStep` in `revalidateAndUpdate` is async, so this code in `handleSubmit` was causing problems:
```
    await revalidateAndUpdate()
    if (!invalidStep) {
      await submit()
      push(`/application/${serialNumber}/submission`)
```
The `invalidStep` value wasn't been set quick enough, so it was still `undefined` for `if(!invalidStep)`. I've changed it so `revalidateAndUpdate` returns `allValid`, and then done this:
```
    const allValid = await revalidateAndUpdate()
    if (allValid) {
      await submit()
      push(`/application/${serialNumber}/submission`)
    }
```

2021-01-07 22:19 UTC, nmadruga commented
Thank you for fixing this, Carl!

I'll reply to your suggestions on this PR.

2021-01-07 23:36 UTC, nmadruga commented on src/components/Main/ModalWarning.tsx
> +import React, { useState } from 'react'
Done

2021-01-07 23:38 UTC, nmadruga commented on src/components/Main/ModalWarning.tsx
> +  const hideModal = () => setShowModal(modalInitialValue)
I have done a little improvement on that now. Please have a look.

I would like to use the ModalProps for setting actions for the Modal window, but that's still a TODO, I'm not entirely sure yet how to use it, but I think we could be using that to make it more generic in the future.

2021-01-07 23:38 UTC, nmadruga commented on src/components/Main/ModalWarning.tsx
> +          {strings.BUTTON_OPTION_YES}
For now I'm defining in each `message`. I don't really like this approach either, but I think we can improve this Modal component as we go.

2021-01-08 04:28 UTC, CarlosNZ approved these changes
Great, it'd be good if you had a look at the suggested changes to the messages, but nothing major.

Any existing weirdness with the Submission page (sometimes) not loading properly I'll address as part of #247.

2021-01-08 04:28 UTC, CarlosNZ commented on src/utils/messages.ts
> +    option: 'Yes',
```suggestion
    option: 'OK',
```
The norm for these kind of buttons is "OK", I think.

2021-01-08 04:28 UTC, CarlosNZ commented on src/utils/messages.ts
> +    title: 'Problem to submit application',
```suggestion
    title: 'Problem submitting application',
```

2021-01-08 04:28 UTC, CarlosNZ commented on src/utils/messages.ts
> +    option: 'Ok',
```suggestion
    option: 'OK',
```

2021-01-10 23:15 UTC, merged