#149 Use password hash for login
openmsupply/application-manager-web-app pull request #256
Opened 2021-01-10 21:00 UTC by CarlosNZ

Implements #149. As discussed in that issue, I've left the "password plugin" to a [separate issue](#253) as there are additional complexities involved with that.

Requires [back-end PR #173](https://github.com/openmsupply/application-manager-server/pull/173) -- most of the logic changes are in there. This front-end is basically just naming/tidying of existing code.

Logging in with one of the existing users (password: "123456") should work with hash comparison on back-end.

2021-01-12 01:58 UTC, nmadruga requested changes
Nice and tidy, I'm having a look on the back-end now.

For now can I just ask something? Can you please also add the encrypted password replace `const hardcodedPassword = '123456'` on the `UserSelection` container so we can continue to login with different test users.

2021-01-12 01:58 UTC, nmadruga commented on src/containers/User/Login.tsx
> +    console.log('Login Result', loginResult)
I think this can be removed now

2021-01-12 02:28 UTC, CarlosNZ commented
> For now can I just ask something? Can you please also add the encrypted password replace `const hardcodedPassword = '123456'` on the `UserSelection` container so we can continue to login with different test users.

This shouldn't need changing -- the password is sent to the server, which compares its hash against the stored one. I think you'll find it's still working okay, no?

Or did you mean something else?

2021-01-14 01:36 UTC, nmadruga commented
> This shouldn't need changing -- the password is sent to the server, which compares its hash against the stored one. I think you'll find it's still working okay, no?

Yes! Sorry, what a confusion/ That's all good! I'll test again and see if this can be already approved

2021-01-14 01:39 UTC, nmadruga approved these changes

2021-01-15 08:16 UTC, merged