#412 Text field error state fix
openmsupply/application-manager-web-app pull request #416
Opened 2021-03-06 02:06 UTC by CarlosNZ

Fixes #412

Not sure why I changed this in the first place -- I think I thought the re-factored `isValid` field would be "true" when the input was still `null` if it wasn't strictly validated. Anyway, it's back to how it was now.

2021-03-06 04:13 UTC, andreievg requested changes
hmm, this makes the required field not appear with a is required error (old and new way)

would suggest something like this: https://github.com/openmsupply/application-manager-web-app/compare/suggested-fix

2021-03-07 21:53 UTC, CarlosNZ commented
> hmm, this makes the required field not appear with a is required error (old and new way)

Yeah, good point!

> would suggest something like this: https://github.com/openmsupply/application-manager-web-app/compare/suggested-fix

I think it can be done without creating a new State variable -- just check `currentResponse.txt` in the place where you were checking the `isValueEmpty` value. Seems to work as expected -- can you see any issues?

143ad29

2021-03-07 22:07 UTC, andreievg commented
>I think it can be done without creating a new State variable -- just check currentResponse.txt in the place where you were checking the isValueEmpty value. Seems to work as expected -- can you see any issues?

This looks way cleaner, thanks !

Just wondering if there is ever a need to check for null ? But otherwise approved

2021-03-07 22:07 UTC, andreievg approved these changes

2021-03-07 22:08 UTC, andreievg commented
btw that approval assumes it's tested now and working (i haven't checked it myself)

2021-03-07 22:13 UTC, CarlosNZ commented
> Just wondering if there is ever a need to check for null ? But otherwise approved

I don't think the .text field can ever be null. It gets a string assigned to it when first initiated (which is when user starts entering info)

> btw that approval assumes it's tested now and working (i haven't checked it myself)

Looking correct to me, strict and normal.

2021-03-07 22:14 UTC, merged