#567 Export data and structure of a table as csv
openmsupply/application-manager-web-app pull request #569
Opened 2021-04-08 12:26 UTC by sworup

2021-04-19 03:44 UTC, andreievg commented
@sworup I am going to review this PR as a whole (rebased to master), to capture all of the changes made (sorry was late at getting this reviewed)

2021-04-19 04:20 UTC, sworup commented
> @sworup I am going to review this PR as a whole (rebased to master), to capture all of the changes made (sorry was late at getting this reviewed)

@andreievg yes seems like the right thing to do as I have changed a lot from the previous base branch in this branch. Better to discard it and rebase this to master.

2021-04-20 03:26 UTC, andreievg requested changes
Hi Sworup,

On most part, code look pretty solid. I've left a few comments (had a look at contexts, hooks and queries). It looks like you've used most of the features of functional react, I wasn't sure why certain features were used (i.e. consumer vs just accessing state with context, and why fragments were used). I am sure the logic is sound, but it's hard to navigate the criss-cross dependencies in state between context, hooks and fragments, typically when the web of dependencies get's so intertwined a diagram is needed (to minimise the time someone new would spend to understanding the logic, or the developer themselves when coming back to make changes in code, or a PR reviewer).

We've been compiling such diagrams, they are in IRMIS/design/UI Workflows (they will eventually make their way into our documentation). One notable one (which was required since complexity of core system was starting to become overwhelming: https://app.diagrams.net/#G1EANnshpdQMk-uCXr7FMrRqIY-ESytIYV).

I've compiled a diagram of how I would implement the lookup table, this is just as an example (don't need to refactor to match my diagram), can you produce a digram with similar detail, to describe lookup table as they are now ? (this would help review the PR and for you to see improvements that can be done to make the code more digestible and to visualise the effects of state changes).

Here is the one I produced: https://app.diagrams.net/#G1OUI8fRnjTyvxBGYgrgpIyBoAk_55mKfu

![lookupTable example diagram](https://user-images.githubusercontent.com/26194949/115331695-7c9cc480-a1ea-11eb-87e7-e8e5baba90ca.png)

Sorry I rushed in making it, so it's a little bit messy.

Btw, my opinionated personal note about React. It seems it's pretty easy to produce a solution in React where dependent elements of code are separated to an extend that it's very hard to visualise their dependencies and how and where states are changed and the effect the state change causes. I personally like the wrapper -> and hook approach, with minimal use of useEffect (one per hook or component if possible, and minimal dependencies in the useEffect). Basically a wrapper would use a hook and render a component or another wrapper, passing through hook results as props (yep, as props, there is a phobia of props use for some reason)

Also I feel that most of the time, context may reduce props propagation, but make components less re-usable and harder to understand (sometimes context are necessary though, for render optimisation or when stage changes need to affect sibling or parent components)

2021-04-20 06:12 UTC, sworup commented on src/LookupTable/contexts/LookUpTableImportCsvContext.tsx
> +  dispatch: React.Dispatch<any>
Resolved with 5cf6edfd and ad95cd6c

2021-04-20 06:15 UTC, sworup commented on src/LookupTable/contexts/LookUpTableImportCsvReducer.tsx
> +        uploadModalOpen: true,
Resolved with 1b8e04dd

2021-04-22 05:58 UTC, sworup commented on src/LookupTable/containers/LookupTableWrapper.tsx
> +                    onImportSuccess={() => getAllTableStructures()}
Resolved with 0b717efd

2021-04-22 05:58 UTC, sworup commented on src/LookupTable/graphql/getTableStructureById.query.ts
> +  query($lookupTableID: Int!) {
Resolved with 0b717efd

2021-04-29 03:32 UTC, andreievg commented
going to merge this one as we need it for demo, @sworup can you transfer the comments I've made to a new issue please

2021-04-29 03:32 UTC, andreievg approved these changes

2021-04-29 03:33 UTC, merged

2021-04-30 11:37 UTC, sworup commented on src/LookupTable/hooks/useGetSingleTable.hook.tsx
> +    const tableName = `${GQL_TABLE_NAME_PREFIX}${capitalizeFirstLetter(
Resolved with 2184f90f

2021-04-30 12:07 UTC, sworup commented on src/LookupTable/components/ImportCsvModal.tsx
> +            <Image src="https://react.semantic-ui.com/images/wireframe/short-paragraph.png" />
Resolved with abe3d502