#662(2) Change Request styles
openmsupply/application-manager-web-app pull request #684
Opened 2021-05-09 10:36 UTC by CarlosNZ

Updates the change request styles to match the latest layout and style changes. Should look pretty much the same as before (with the coloured borders around the elements).

<img width="529" alt="Screen Shot 2021-05-09 at 10 34 31 PM" src="https://user-images.githubusercontent.com/5456533/117568842-cb1cef00-b116-11eb-8d66-a2795d074263.png">

@nmadruga -- I have tried to preserve the conditional logic for the colour/style display in ApplicationViewWrapper using simple class switching rather than inline styles, but it'd be worth having a careful look at that bit to make sure.

- Also updated the "Make Changes" style in Applications List.

2021-05-10 11:02 UTC, nmadruga requested changes
Very nice. It looks way tidier like that.

I have noticed one tiny issue: I think the colour for the icon here should be blue:
<img width="339" alt="Screen Shot 2021-05-10 at 10 59 49 PM" src="https://user-images.githubusercontent.com/16461988/117649366-89a64580-b1e3-11eb-88e1-d62117f97084.png">

Also there is something different on the `info` icon  regarding alignment, it looks different from the alert one for some reason:
<img width="94" alt="Screen Shot 2021-05-10 at 11 01 07 PM" src="https://user-images.githubusercontent.com/16461988/117649515-b5c1c680-b1e3-11eb-8686-73683d84ca50.png">

2021-05-10 11:05 UTC, nmadruga commented on src/components/List/Cells/StatusCell.tsx
> +          <Icon name="trash alternate outline" />
Hmm actually something is still missing, this "edit draft" should be showing with similar alignment to "make changes":

<img width="900" alt="Screen Shot 2021-05-10 at 11 04 19 PM" src="https://user-images.githubusercontent.com/16461988/117649898-2b2d9700-b1e4-11eb-92fd-1cdaafa0317f.png">
<img width="900" alt="Screen Shot 2021-05-10 at 11 03 34 PM" src="https://user-images.githubusercontent.com/16461988/117649901-2cf75a80-b1e4-11eb-8c30-2f0e81883749.png">

2021-05-10 21:37 UTC, CarlosNZ commented
>  have noticed one tiny issue: I think the colour for the icon here should be blue:
> <img alt="Screen Shot 2021-05-10 at 10 59 49 PM" width="339" src="https://user-images.githubusercontent.com/16461988/117649366-89a64580-b1e3-11eb-88e1-d62117f97084.png">

Yes, good catch. Thanks. Turns out the logic was correct (same as yours previously), but hadn't defined the "blue" class. 🙄

Have called the class "interactive-color", as I think "blue" will clash with existing classes. 9f13ff04

Quick question: Do you think the text should be blue as well, or just the icon? Here it is with both:
![Screen Shot 2021-05-11 at 9 36 21 AM](https://user-images.githubusercontent.com/5456533/117727626-63f95a80-b23c-11eb-896c-8861905f52df.png)

2021-05-10 21:43 UTC, CarlosNZ commented on semantic/src/site/globals/site.overrides
> +  font-size: 0.9em;
Okay, I've made some additional relative size text size variables. We can probably consolidate these down to just one or two at some point, but will wait until we see the whole thing in context. 62f9ccbd

2021-05-10 21:45 UTC, CarlosNZ commented
> Also there is something different on the `info` icon regarding alignment, it looks different from the alert one for some reason:

I'm not seeing it. 😕 What are you referring to exactly?

2021-05-10 21:52 UTC, CarlosNZ commented on src/components/List/Cells/StatusCell.tsx
> +          <Icon name="trash alternate outline" />
Thanks, done: e5f84f6c

I notice that the "Trash" icon doesn't actually do anything yet. Have added a "TO-DO" in the code, but do you think we should maybe hide it for now?

2021-05-10 21:55 UTC, CarlosNZ commented on src/formElementPlugins/ApplicationViewWrapper.tsx
> +          : 'info circle'
Good idea, it's much cleaner now: 733d4ecf

2021-05-11 22:33 UTC, nmadruga commented
> Quick question: Do you think the text should be blue as well, or just the icon? Here it is with both:
> ![Screen Shot 2021-05-11 at 9 36 21 AM](https://user-images.githubusercontent.com/5456533/117727626-63f95a80-b23c-11eb-896c-8861905f52df.png)

Looks great to me

2021-05-11 22:34 UTC, nmadruga commented
> > Also there is something different on the `info` icon regarding alignment, it looks different from the alert one for some reason:
> 
> I'm not seeing it. 😕 What are you referring to exactly?

It seemed not aligned to me, but now all in blue it seems good, so probably nothing.

2021-05-11 23:35 UTC, merged