#674 replace actions filter from number to enum type
openmsupply/application-manager-web-app pull request #722
Opened 2021-05-19 01:33 UTC by nmadruga

Fixes #674 

### Needs back-end issue in PR
TODO

### Changes
- Replace counts (to set review_actions) for a new `reviewer_action` ENUM
- Fix query to use new filter as enum - not testes
- WIP - Fix filters on Dashboard
- WIP - Replace counts for assigner_action with new ENUM

2021-05-20 00:45 UTC, nmadruga commented
This is ready for a re-review now. I have finished all the work-in-progress

2021-05-20 04:32 UTC, andreievg requested changes
This is all working very well.

Can you add assignerAction to `buildQueryFilters` and change the last two filters in back end to use assignerActions please (i've checked it seems to work with those changes)

2021-05-23 04:48 UTC, nmadruga commented
> This is all working very well.
> 
> Can you add assignerAction to `buildQueryFilters` and change the last two filters in back end to use assignerActions please (i've checked it seems to work with those changes)

Done

2021-05-23 10:06 UTC, andreievg approved these changes

2021-05-24 00:44 UTC, merged