#787 Update inline decision with designs (option 2)
openmsupply/application-manager-web-app pull request #790
Opened 2021-06-15 05:18 UTC by nmadruga

Fixes #787

### Linked branches
based on PR #788 

### Changes

As described in the issue, there are 3 cases to update with latest designs (using Option 2):
- [x] Review new applicant response
- [x] Update your review (after changes-requested by Consolidator)
- [ ] Review other review (Consolidation, basically) - Work in progress...

#### Designs
<img width="361" alt="Screen Shot 2021-06-15 at 5 10 20 PM" src="https://user-images.githubusercontent.com/16461988/121996383-9e868200-cdfc-11eb-84fb-26a31762af37.png">

Although keep in mind that we are limiting to show only 3 maximum of response-elements (anything that was submitted by one of the applicant's reviewer or the applicant himself). Soon we will have the "Show history" option to list anything else more than the latest 3. : )

#### Current - Applicant new/first response:
<img width="636" alt="Screen Shot 2021-06-15 at 5 16 52 PM" src="https://user-images.githubusercontent.com/16461988/121996934-9c70f300-cdfd-11eb-9c61-060eab45b1e0.png">
<img width="632" alt="Screen Shot 2021-06-15 at 5 17 11 PM" src="https://user-images.githubusercontent.com/16461988/121996928-99760280-cdfd-11eb-8207-ee307e42082d.png">
Have tried to only change things strict related to this, with help from @CarlosNZ was able to not need to change existing less files so much - only added the `blue-border` around what needs to be in context with inline-decision and that's it.

We agreed that we won't have a duplicate text version of the Applicant's response, so using straight Applicant response

#### Current - Reviewer changes-requested:
<img width="651" alt="Screen Shot 2021-06-15 at 4 49 38 PM" src="https://user-images.githubusercontent.com/16461988/121996392-a21a0900-cdfc-11eb-85b1-c4c948c5f99d.png">
<img width="634" alt="Screen Shot 2021-06-15 at 4 44 55 PM" src="https://user-images.githubusercontent.com/16461988/121996393-a21a0900-cdfc-11eb-9184-4955acc09913.png">

#### Current - Consolidation first/second reviews
 
### Problems
**TODO**: Tiny problem on the top of blu-border collides with what is defined in here:
https://github.com/openmsupply/application-manager-web-app/blob/df78130bfea234e9474cb1943ad2c458cb17880a/semantic/src/site/globals/site.overrides#L849-L857
not sure how to fix that... Some review's help wanted : )

2021-06-16 03:19 UTC, CarlosNZ requested changes
~~Might not have been done in this branch~~ (It was, just checked the base branch), but somehow the rounded border on the bottom of the review elements is missing now:
![Screen Shot 2021-06-16 at 3 16 48 PM](https://user-images.githubusercontent.com/5456533/122152838-f8974e00-ceb5-11eb-839a-0cd717074371.png)

How it should look (on master):
![Screen Shot 2021-06-16 at 3 16 03 PM](https://user-images.githubusercontent.com/5456533/122152852-fd5c0200-ceb5-11eb-97d0-3f03f041a6a7.png)

I suspect it's something to do with how the elements are nested -- the "last-child" properties are not being applied to the bottom response-container in the segment.

2021-06-18 03:17 UTC, nmadruga commented on semantic/src/site/globals/site.overrides
> +}
Ta : )

2021-06-18 03:26 UTC, nmadruga commented
Quick fix done. Can this be merged?

Please note: if this PR is run with back-end using `yarn pg_permissions` it will have some missing elements due to currently one reviewer  not having permission to view others reviews. There should be a PR to fix created today. : )

2021-06-18 03:46 UTC, CarlosNZ approved these changes

2021-06-18 04:01 UTC, merged