Demo server guide
openmsupply/application-manager-web-app pull request #922
Opened 2021-08-23 00:30 UTC by CarlosNZ

Just quickly added this doc for updating the demo server.

2021-08-23 03:30 UTC, nmadruga requested changes
Nice to have that in here. Just one missing item (probably from my original document)

2021-08-23 03:30 UTC, nmadruga commented on docs/internal/demo-server-guide.md
> +   `docker push <image_id> /<docker-repo>:<tag-name>`
```suggestion
  `docker tag <image_id> <organisation>/<docker-repo>:<tag-name>`
- Push new tag:  
   `docker push <image_id> <organisation>/<docker-repo>:<tag-name>`  
```

2021-08-23 03:30 UTC, nmadruga commented on docs/internal/demo-server-guide.md
> +- How to check Env vars?
$ printenv

Right?

2021-08-23 08:17 UTC, CarlosNZ commented on docs/internal/demo-server-guide.md
> +- How to check Env vars?
Great, thanks!!

2021-08-24 10:56 UTC, nmadruga approved these changes

2021-08-24 21:10 UTC, merged

2021-08-24 21:28 UTC, CarlosNZ commented
FYI -- I just realised that this should really be in back-end docs, so I've moved it across to there (done directly in `develop`)